language: "shell"
sudo: "true"
branches:
  only:
    - master
script:
  - sudo yum install -y gcc openssl-devel.x86_64 git cmake make gcc-c++
  - curl https://sh.rustup.rs -o rustup.sh
  - chmod +x rustup.sh
  - ./rustup.sh -y
  - git clone https://github.com/google/flatbuffers  flatbuffers
  - cd flatbuffers
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - sudo cp flatc /usr/local/bin/flatc
  - cd ..
  - ~/.cargo/bin/cargo test
