[package]
name = "api"
version = "0.1.0"
authors = ["Michelle Zhong <Michelle_Zhong@comcast.com>", "Chris Holcombe <xfactor973@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
protobuf = "~2"

[build-dependencies]
protobuf-codegen-pure = "2.3"